apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oc-provider-ingress
  namespace: oc-provider
  annotations:
    cert-manager.io/cluster-issuer: local-ca-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - provider.localhost
      secretName: provider-localhost-tls
  rules:
    - host: provider.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oc-provider-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: oc-provider-backend
                port:
                  number: 80
