apiVersion: v1
kind: Namespace
metadata:
  name: oc-provider
---
apiVersion: v1
kind: Namespace
metadata:
  name: oc-client
---
apiVersion: v1
kind: Namespace
metadata:
  name: oc-gateway
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

