apiVersion: v1
kind: Service
metadata:
  name: oc-client-backend-dev
  namespace: oc-client
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: oc-client-backend-dev
  namespace: oc-client
subsets:
  - addresses:
      - ip: 192.168.65.254  # host.k3d.internal IP
    ports:
      - name: http
        port: 3000
