apiVersion: v1
kind: Service
metadata:
  name: oc-provider-frontend-dev
  namespace: oc-provider
spec:
  type: ExternalName
  externalName: host.k3d.internal
  ports:
    - name: http
      port: 9000
      targetPort: 9000
