apiVersion: v1
kind: Service
metadata:
  name: oc-provider-backend-dev
  namespace: oc-provider
spec:
  type: ExternalName
  externalName: host.k3d.internal
  ports:
    - name: http
      port: 3000
      targetPort: 3000